"""
Copyright (c) All Rights Reserved 

THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND EXPRESS
OR IMPLIED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED 
IN THIS NOTICE BE LIABLE FOR ANY CLAIM OR CONSEQUENTIAL DAMAGES OR ANY 
DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE DATA OR PROFITS, WHETHER
IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Author Taylor Lopes <taylorlopes@gmail.com>
""" 

# Configuração para testes

USUARIO_ID = "9a9a6995-4403-49cc-8214-797e12e68909"
USUARIO_NOME = "User Test"
USUARIO_EMAIL = "user@test.com"
USUARIO_SENHA = "123456"
CARTEIRA_ID = "aff23298-079a-4f24-a064-668d49fd9501"
ATIVO_ID = "b39f9a8d-ef86-47a6-8dd2-d3cfb32ed5c9"
TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5YTlhNjk5NS00NDAzLTQ5Y2MtODIxNC03OTdlMTJlNjg5MDkiLCJuYW1lIjoiVXNlciBUZXN0IiwiZW1haWwiOiJ1c2VyQHRlc3QuY29tIiwicm9sZXMiOlsiVVNFUl9BUFAiXSwiaWF0IjoxNzE2MzgzNDcyLCJleHAiOjE3MTY0MjY2NzJ9.NqtZj5OAM0yljnSCCkUBPg-8wrZuZXlSkDT5jqpt96o"

